### 회원가입
POST http://localhost:8080/api/auth/signUp
Content-Type: application/json

{
  "email": "hagaji3@naver.com",
  "password": "12345",
  "nickname": "abcd",
  "phoneNumber": "010-1234-5678"
}

### 로그인
POST http://localhost:8080/api/auth/signIn
Content-Type: application/json

{
  "email": "hagaji3@naver.com",
  "password": "12345"
}

### 이메일 인증
POST http://localhost:8080/api/auth/mail/certification
Content-Type: application/json

{
  "email": "hagaji3@naver.com"
}

### 이메일 검증
POST http://localhost:8080/api/auth/mail/verify
Content-Type: application/json

{
  "email": "hagaji3@naver.com",
  "code": "159919"
}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcwNzQ5MDg0MywiZXhwIjoxNzA3NDkyNjQzfQ.bD_2irVodHczNUnAnrvB1rlVMobeQ09f-pvvs-7f_ZE"
}


### 토큰 재발급
POST http://localhost:8080/api/auth/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcwNzQ5MDg0MywiZXhwIjoxNzA3NDkyNjQzfQ.bD_2irVodHczNUnAnrvB1rlVMobeQ09f-pvvs-7f_ZE",
  "refreshToken": "Logout"
}